- name: Install Docker
  hosts: ivanka1212171.mylabserver.com
  tasks:
    - name: Install Docker
      yum:
        name: docker-ce
        state: present
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true
