- name: Install Docker
  hosts: all
  tasks:
    - name: Install Docker
      yum:
        name: docker-ce
        state: present
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true
